# -*- coding: utf-8 -*-
"""Shantonu Das(KEC 3622).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wf0dEs0gJ7mvqAxI390g0yUgp3ffHyYb
"""

class Contact:
    def __init__(self, name, phone, email):
        self.name = name
        self.phone = phone
        self.email = email

def add_contact():
    name = input("Enter name: ")
    phone = input("Enter phone number: ")
    email = input("Enter email: ")
    new_contact = Contact(name, phone, email)
    contacts.append(new_contact)
    print("Contact added successfully!")

def display_contacts():
    if not contacts:
        print("No contacts found.")
    else:
        print("Contacts:")
        for i, contact in enumerate(contacts):
            print(f"{i+1}. Name: {contact.name}, Phone: {contact.phone}, Email: {contact.email}")

def search_contact():
    name = input("Enter name to search: ")
    for contact in contacts:
        if contact.name.lower() == name.lower():
            print(f"Name: {contact.name}, Phone: {contact.phone}, Email: {contact.email}")
            return
    print("Contact not found.")

def delete_contact():
    name = input("Enter name to delete: ")
    for i, contact in enumerate(contacts):
        if contact.name.lower() == name.lower():
            del contacts[i]
            print("Contact deleted successfully!")
            return
    print("Contact not found.")

if __name__ == "__main__":
    contacts = [ ]

    while True:
        print("\nContact Book Menu:")
        print("1. Add Contact")
        print("2. Display Contacts")
        print("3. Search Contact")
        print("4. Delete Contact")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")

        if choice == '1':
            add_contact()
        elif choice == '2':
            display_contacts()
        elif choice == '3':
            search_contact()
        elif choice == '4':
            delete_contact()
        elif choice == '5':
            print("Exiting...")
            break
        else:
            print("Invalid choice. Please try again.")